version: '3.4'

services:
  polkadot_common_exporter:
    build:
      context: ./exporters/common
      args:
        exporter: "common_exporter"
    environment:
      - "LISTEN=0.0.0.0"
      - "PORT=9150" 
      - "CHAIN=${NETWORK}"
    env_file:
      - ./custom-polkadot.env
    networks:
      - exporters
      - default
    restart: unless-stopped
    labels:
      - traefik.enable=false
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9150
      - metrics.instance=polkadot
      - metrics.network=${NETWORK}

  polkadot_finality_exporter:
    build:
      context: ./exporters/common
      args:
        exporter: "finality_exporter"
    environment:
      - "LISTEN=0.0.0.0"
      - "PORT=9150"
      - "CHAIN=${NETWORK}"
    env_file:
      - ./custom-polkadot.env
    networks:
      - exporters
      - default
    restart: unless-stopped
    labels:
      - traefik.enable=false
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9150
      - metrics.instance=polkadot
      - metrics.network=${NETWORK}

  polkadot_events_exporter:
    build:
      context: ./exporters/events
    networks:
      - exporters
      - default
    env_file:
      - ./custom-polkadot.env
    restart: unless-stopped
    labels:
      - traefik.enable=false
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9150
      - metrics.instance=polkadot
      - metrics.network=${NETWORK}
