version: '3.4'

services:
  redis:
    image: redis:latest
    command: ["redis-server"]
    networks:
      - monitoring
      - default
    restart: unless-stopped

  validators_cache:
    build:
      context: ./validators_cache
    networks:
      - redis
      - monitoring
      - default
    restart: unless-stopped

  github_release_exporter:
    build:
      context: ./exporters/github_release
    environment:
      - "LISTEN=0.0.0.0"
      - "PORT=9150"
    networks:
      - exporters
      - default
    restart: unless-stopped
    labels:
      - traefik.enable=false
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9150
      - metrics.instance=polkadot
      - metrics.network=${NETWORK}

volumes:
    prometheus_data: {}
    prometheus_rules: {}
    grafana_data: {}
    alertmanager-data: {}
    pgadmin: {}

networks:
  exporters: 
  monitoring:
  redis:
