version: '3.4'

services:
  karura_exporter:
    build:
      context: ./exporters/acala
    environment:
    - "LISTEN=0.0.0.0"
    - "PORT=9150" 
    - "CHAIN=karura"
    env_file:
    - ./karura.env
    networks:
    - exporters

