version: '3.4'

services:
  kusama_common_exporter:
    build:
      context: ./exporters/common
      args:
        exporter: "common_exporter"
    environment:
    - "LISTEN=0.0.0.0"
    - "PORT=9150" 
    - "CHAIN=kusama"
    env_file:
    - ./kusama.env
    networks:
    - exporters
    restart: on-failure

  kusama_finality_exporter:
    build:
      context: ./exporters/common
      args:
        exporter: "finality_exporter"
    environment:
    - "LISTEN=0.0.0.0"
    - "PORT=9150"
    - "CHAIN=kusama"
    env_file:
    - ./kusama.env
    networks:
    - exporters
    restart: on-failure

  kusama_events_exporter:
    build:
      context: ./exporters/events
    networks:
    - exporters
    env_file:
    - ./kusama.env
    restart: on-failure
