---
## Please never rename alert names without corresponding migration in DB
groups:
- name: maas-rules
  rules:
  - alert: Validator left set
    expr: polkadot_session_disabledValidators == 1
    for: 1m
    labels:
      severity: "critical"
    annotations:
      summary: "{{ $labels.account }}: Validator has been kicked from the active set."
      description: "Validator {{ $labels.account }} has been kicked from the active set."
      chain: "{{ $labels.chain }}"
      account: "{{ $labels.account }}"

  - alert: Low GRANDPA precommits ratio
    expr: (polkadot_finality_precommits{chain="polkadot"} / on (chain) group_left() polkadot_finality_roundsProcessed * 100) < 10 and on(node) polkadot_session_validators == 1 and on (chain) polkadot_session_sessionProgress >= 3
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "{{ $labels.account }}: Validator has problem with block finality(precommits) less than 10%"
      description: "Validator {{ $labels.account }} has problem with block finality(precommits) less than 10%"
      chain: "{{ $labels.chain }}"
      account: "{{ $labels.account }}"

  - alert: Low GRANDPA prevotes ratio
    expr: (polkadot_finality_prevotes{chain="polkadot"} / on (chain) group_left() polkadot_finality_roundsProcessed * 100) < 80 and on(node) polkadot_session_validators == 1 and on (chain) polkadot_session_sessionProgress >= 3
    for: 2m
    labels:
      severity: high
    annotations:
      summary: "{{ $labels.account }}: Validator has problem with block finality(prevotes) less than 80%"
      description: "Validator {{ $labels.account }} has problem with block finality(prevotes) less than 80%"
      chain: "{{ $labels.chain }}"
      account: "{{ $labels.account }}"
