global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
- 'rules/*.yml'

scrape_configs:
- job_name: polkadot_common_exporter
  metrics_path: /metrics
  static_configs:
  - targets:
    - 'polkadot_common_exporter:9150'

- job_name: kusama_common_exporter
  metrics_path: /metrics
  static_configs:
  - targets:
    - 'kusama_common_exporter:9150'

- job_name: polkadot_finality_exporter
  metrics_path: /metrics
  static_configs:
  - targets:
    - 'polkadot_finality_exporter:9150'
        
- job_name: kusama_finality_exporter
  metrics_path: /metrics
  static_configs:
  - targets:
    - 'kusama_finality_exporter:9150'

- job_name: polkadot_events_exporter
  metrics_path: /metrics
  static_configs:
  - targets:
    - 'polkadot_events_exporter:9150'

- job_name: kusama_events_exporter
  metrics_path: /metrics
  static_configs:
  - targets:
    - 'kusama_events_exporter:9150'

- job_name: moonbeam_exporter
  metrics_path: /metrics
  static_configs:
  - targets:
    - 'moonbeam_exporter:9150'

- job_name: moonriver_exporter
  metrics_path: /metrics
  static_configs:
  - targets:
    - 'moonriver_exporter:9150'

- job_name: acala_exporter
  metrics_path: /metrics
  static_configs:
  - targets:
    - 'acala_exporter:9150'

- job_name: karura_exporter
  metrics_path: /metrics
  static_configs:
  - targets:
    - 'karura_exporter:9150'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]
