name: lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Promtool:
    name: Promtool
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Check Prometheus config
      uses: peimanja/promtool-github-actions@master
      with:
        promtool_actions_subcommand: 'config'
        promtool_actions_files: 'prometheus/prometheus.yml'
        promtool_actions_version: 2.50.0
        promtool_actions_comment: true
